<?php

namespace Anaxago\CoreBundle\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    public function findWithInteret($user)
    {
        return $this->createQueryBuilder('u')
            ->leftJoin('u.projects', 'p')
            ->where('u.id = :user')
            ->setParameter('user', $user->getId())
            ->getQuery()
            ->getSingleResult();;
    }
}
